apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: bharath0812/nodepro:1.0
        ports:
        - containerPort: 1004
---
apiVersion: v1
kind: Service
metadata:
 name: cart-svc
spec:
  type: ClusterIP
  selector:
   app: cart
  ports:
   - port: 80
     targetPort: 1004

