apiVersion: apps/v1
kind: Deployment
metadata:
  name: eur-deployment
  labels:
    app: eur
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eur
  template:
    metadata:
      labels:
        app: eur
    spec:
      containers:
      - name: eur
        image: bharath0812/nodepro:5.0
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
 name: eur-svc
spec:
  type: ClusterIP
  selector:
   app: eur
  ports:
   - port: 8084
     targetPort: 8761
