apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoes-deployment
  labels:
    app: shoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoes
  template:
    metadata:
      labels:
        app: shoes
    spec:
      containers:
      - name: shoes
        image: bharath0812/nodepro:6.0
        ports:
        - containerPort: 1002
---
apiVersion: v1
kind: Service
metadata:
 name: shoes-svc
spec:
  type: ClusterIP
  selector:
   app: shoes
  ports:
   - port: 8086
     targetPort: 1002
